# [START gae_java11_helloworld_yaml]
runtime: java11
instance_class: F1
# Explicitly set the memory limit and maximum heap size for the Spring Boot app
env_variables:
  JAVA_TOOL_OPTIONS: "-XX:MaxRAM=512m -XX:ActiveProcessorCount=2 -Xmx32m"
# [END gae_java11_helloworld_yaml]
handlers:
  - url: /.*
    script: auto
    secure: always
    redirect_http_response_code: 301
